Keep pulumi/sdk/v3 and pulumi/pkg/v3 in sync
Fixes these errors:
```
# github.com/pulumi/pulumi/pkg/v3/resource/deploy/deploytest
../../../golang/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.33.1/resource/deploy/deploytest/pluginhost.go:247:9: cannot use &pluginHost{…} (value of type *pluginHost) as type plugin.Host in return statement:
        *pluginHost does not implement plugin.Host (missing ResolvePlugin method)
../../../golang/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.33.1/resource/deploy/deploytest/pluginhost.go:288:35: cannot use host (variable of type *pluginHost) as type plugin.Host in argument to best.loadWithHost:
        *pluginHost does not implement plugin.Host (missing ResolvePlugin method)
```

Signed-off-by: Ringo De Smet <ringo@de-smet.name>